config/routes.rb
Rails.application.routes.draw do
  resources :resources
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: %i[ show edit update destroy ]

  # GET /resources or /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1 or /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources or /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to resource_url(@resource), notice: "Resource was successfully created." }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1 or /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to resource_url(@resource), notice: "Resource was successfully updated." }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1 or /resources/1.json
  def destroy
    @resource.destroy

    respond_to do |format|
      format.html { redirect_to resources_url, notice: "Resource was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resource_params
      params.require(:resource).permit(:name, :description, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
    <div id="app"></div>
  </body>
</html>

app/views/resources/_form.html.erb
<%= form_with(model: resource) do |form| %>
  <% if resource.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div id="<%= dom_id resource %>">
  <p>
    <strong>Name:</strong>
    <%= resource.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= resource.description %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= resource.active %>
  </p>

</div>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render "form", resource: @resource %>

<br>

<div>
  <%= link_to "Show this resource", @resource %> |
  <%= link_to "Back to resources", resources_path %>
</div>

app/views/resources/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Resources</h1>

<div id="resources">
  <% @resources.each do |resource| %>
    <%= render resource %>
    <p>
      <%= link_to "Show this resource", resource %>
    </p>
  <% end %>
</div>

<%= link_to "New resource", new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render "form", resource: @resource %>

<br>

<div>
  <%= link_to "Back to resources", resources_path %>
</div>

app/views/resources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @resource %>

<div>
  <%= link_to "Edit this resource", edit_resource_path(@resource) %> |
  <%= link_to "Back to resources", resources_path %>

  <%= button_to "Destroy this resource", @resource, method: :delete %>
</div>